name: service-container-test

on:
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest

    services:
      flask-app:
        image: ghcr.io/akshayeanil/simple-flask-app:latest
        ports:
          - 5000:5000
        options: >-
          --health-cmd="curl -f http://localhost:5000 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Wait for container to be healthy
        run: |
          echo "Waiting for the flask app to become healthy..."
          sleep 20

      - name: Test the Flask app container
        run: |
          curl --fail http://localhost:5000 || exit 1
